### ISSUE TITLE
As a user experience manager I want to understand the types of text users are putting in. 

### ISSUE THREAD

**Issue by vronvali** [iLanguage/iLanguageCloud#76]
- [x] Replicate the database to localhost 
https://localhost:6984/_utils/database.html?anonymouswordclouduser1401365327718-firstcorpus/_design/user_experience/_view/detect_erroneous_enter_key

- [x] Query the database for all texts. (do in javaScript)
```javascript
map: 
function(doc) {
  emit(doc.originalText.length, [new Date(doc.dateCreated),  doc.originalText.length, doc.originalText]);
}
```
- [x]  Sort text by length. 
```javascript
reduce: 
_count
```

![screen shot 2015-06-05 at 6 36 03 pm](https://cloud.githubusercontent.com/assets/12688769/8016483/e9cd991a-0bb1-11e5-9e5b-f9c0d79b184a.png)

- [ ]  Group text by user to see how many texts users make on average. 
- [ ] Try to group user by type based on the length of what they write. (Do in a Spreadsheet)

**Comment by vronvali** [comment]
![screen shot 2015-06-08 at 2 37 59 pm](https://cloud.githubusercontent.com/assets/12688769/8042255/0b97c55c-0dec-11e5-9fea-df3291a73110.png)

**Comment by cesine** [comment]
@vronvali  i think the standard deviation chart is best viewed as a box plot, have you seen those before? https://github.com/OpenSourceFieldlinguistics/FieldDB/issues/2008

example: 

https://developers.google.com/chart/interactive/docs/gallery/candlestickchart
![screen shot 2015-06-08 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/196199/8042342/b49d237c-0dec-11e5-91cf-968f2cd89b55.png)


we can move on to the tests now that we have an idea of what we want for categories, and use box plots next time you have to do histograms
